FROM node:16

WORKDIR /app

# Copy package files
COPY package*.json ./
RUN npm install

# Copy source code
COPY . ./

# Expose port for development
EXPOSE 3000

# Start development server with hot reload
CMD ["npm", "start"]
#docker run -p 3000:3000 -v ${PWD}/src:/app/src react-app-dev